// GENERATED by scripts/octane-vendor.sh — do not edit by hand.
//
// Run chunk for the richards workload: 32 fixed iterations, measured
// per op. Depends on globals the setup chunk defined, which survive
// because Interpret() does not Reset().
for (var __octane_i = 0; __octane_i < 32; __octane_i++) { runRichards(); }
true;
