// GENERATED by scripts/octane-vendor.sh — do not edit by hand.
//
// Run chunk for the splay workload: 20 fixed iterations, measured
// per op. Depends on globals the setup chunk defined, which survive
// because Interpret() does not Reset().
for (var __octane_i = 0; __octane_i < 20; __octane_i++) { SplayRun(); }
true;
