package vm

import "testing"

// The long-jump opcodes (OpJumpLong / OpJumpIfFalseLong) carry a 32-bit relative
// offset so machine-generated bytecode (the wasm transpiler) can encode jumps
// past the ±32 KB int16 range. The stock TS compiler never emits them. These
// tests exercise the decode with small offsets — the wasm asm layer covers the
// promotion/relaxation that produces genuinely large offsets.

func run(t *testing.T, c *Chunk) float64 {
	t.Helper()
	res, errs := NewVM().Interpret(c)
	if len(errs) > 0 {
		t.Fatalf("interpret: %v", errs)
	}
	return res.ToFloat()
}

func TestOpJumpLongSkipsPoison(t *testing.T) {
	c := NewChunk()
	poison := c.AddConstant(Number(11))
	want := c.AddConstant(Number(99))

	c.WriteOpCode(OpJumpLong, 1)
	c.WriteUint32(4) // skip the 4-byte poison OpLoadConst below

	c.WriteOpCode(OpLoadConst, 1) // poison: unreachable if the jump lands right
	c.EmitByte(0)
	c.WriteUint16(poison)

	c.WriteOpCode(OpLoadConst, 1) // jump target
	c.EmitByte(0)
	c.WriteUint16(want)
	c.WriteOpCode(OpReturn, 1)
	c.EmitByte(0)
	c.MaxRegs = 1

	if got := run(t, c); got != 99 {
		t.Fatalf("OpJumpLong: got %v, want 99 (poison not skipped)", got)
	}
}

func TestOpJumpIfFalseLong(t *testing.T) {
	// cond=0 (falsey) → jump taken → returns 99; cond=1 → falls through → 11.
	build := func(cond float64) *Chunk {
		c := NewChunk()
		condC := c.AddConstant(Number(cond))
		poison := c.AddConstant(Number(11))
		want := c.AddConstant(Number(99))

		c.WriteOpCode(OpLoadConst, 1)
		c.EmitByte(0)
		c.WriteUint16(condC)

		c.WriteOpCode(OpJumpIfFalseLong, 1)
		c.EmitByte(0)      // condReg R0
		c.WriteUint32(6)   // skip the 6-byte fall-through block below

		c.WriteOpCode(OpLoadConst, 1) // fall-through (cond truthy)
		c.EmitByte(1)
		c.WriteUint16(poison)
		c.WriteOpCode(OpReturn, 1)
		c.EmitByte(1)

		c.WriteOpCode(OpLoadConst, 1) // jump target (cond falsey)
		c.EmitByte(1)
		c.WriteUint16(want)
		c.WriteOpCode(OpReturn, 1)
		c.EmitByte(1)
		c.MaxRegs = 2
		return c
	}

	if got := run(t, build(0)); got != 99 {
		t.Fatalf("OpJumpIfFalseLong(false): got %v, want 99 (jump not taken)", got)
	}
	if got := run(t, build(1)); got != 11 {
		t.Fatalf("OpJumpIfFalseLong(true): got %v, want 11 (jump wrongly taken)", got)
	}
}

// Reset must drop the constant-dedup caches, not just truncate Constants — else
// AddConstant returns a stale index past the shorter pool (the bug that made a
// spilled wasm function load constant 67 from a 25-entry pool).
func TestChunkResetClearsConstCaches(t *testing.T) {
	c := NewChunk()
	for i := 0; i < 40; i++ {
		c.AddConstant(Number(float64(i))) // ints 0..39 → indices 0..39
	}
	c.Reset()
	if idx := c.AddConstant(Number(37)); idx != 0 {
		t.Fatalf("after Reset, AddConstant returned stale index %d (want 0)", idx)
	}
	if len(c.Constants) != 1 {
		t.Fatalf("after Reset + one add, pool has %d constants (want 1)", len(c.Constants))
	}
}
