#!/usr/bin/env bash
# Vendor the Octane workloads into tests/scripts/octane/ as fixtures the pinned
# benchmark corpus can overlay onto any commit.
#
# Usage: scripts/octane-vendor.sh [--src DIR]
#
#   --src DIR   a chromium/octane checkout (default: benchmarks/octane, which
#               is gitignored; clone it with
#               git clone --depth 1 https://github.com/chromium/octane.git)
#
# WHY VENDOR RATHER THAN FETCH
#
# bench-corpus.sh may only overlay _test.go files and tests/scripts fixtures,
# because anything else would measure a different engine than the commit under
# test. A fetched benchmarks/ directory can therefore never be part of a pinned
# session, and a benchmark that cannot be pinned cannot measure history. The
# sources are third-party and frozen, which makes them an unusually good
# instrument: the corpus varies the engine and nothing else.
#
# WHY TWO FILES PER WORKLOAD
#
# Everything a benchmark does per iteration is measured, including work that is
# not the workload. Ten of the previous 35 benchmarks turned out to be measuring
# engine startup (nooga#51). The same trap is waiting here in two forms:
# executing 200KB of top-level definitions, and Splay's setup, which builds a
# large tree and costs ~0.6s against a ~14ms iteration.
#
# So each workload emits a pair:
#
#   <name>.js       base.js + the workload + ResetRNG + setup()  -- run ONCE,
#                   before the timer starts
#   <name>-run.js   the fixed-iteration loop over the workload   -- run per op
#
# The split relies on VM.Interpret NOT calling Reset(): user globals and the
# inline cache persist across chunks, so the run chunk sees what the setup chunk
# defined. That is load-bearing, and bench_octane_test.go fails loudly (undefined
# global) rather than silently if it ever stops being true.
#
# WHY ITERATION COUNTS ARE BAKED IN, NOT TIMED
#
# Octane scores itself: it runs for ~1s and reports iterations achieved. That
# puts host noise directly into the number -- observed here swinging 101 to 178
# on two runs of one binary. Fixed work measured by an external timer read 0.38s
# five times running. The counts below target ~0.3s of work per op, derived by
# measuring K=1 and K=11 and subtracting, so setup is not folded into the
# per-iteration figure.
set -euo pipefail

die() { echo "error: $*" >&2; exit 1; }
note() { echo "==> $*" >&2; }

SRC="benchmarks/octane"
while [ $# -gt 0 ]; do
  case "$1" in
    --src) SRC="${2:?}"; shift 2;;
    -h|--help) sed -n '2,12p' "$0"; exit 0;;
    *) die "unknown option: $1";;
  esac
done

repo="$(git rev-parse --show-toplevel)" || die "not in a git repo"
cd "$repo"
[ -d "$SRC" ] || die "no octane checkout at $SRC — clone chromium/octane there first"
[ -f "$SRC/base.js" ] || die "$SRC has no base.js; is it really a chromium/octane checkout?"

SRC_SHA="$(git -C "$SRC" rev-parse --short HEAD 2>/dev/null || echo unknown)"
DEST="tests/scripts/octane"
mkdir -p "$DEST"

# name:setup:run:teardown:iterations
#
# RegExp is deliberately absent: it fails "Wrong checksum" on every engine in
# the measured window, so it is a correctness bug to fix, not a benchmark to
# run. Crypto pairs encrypt with decrypt because decrypt reads the global that
# encrypt sets and then verifies the round trip, which makes the pair
# self-checking. EarleyBoyer likewise runs both halves Octane scores together.
SPECS=(
  "richards::runRichards();::32"
  "deltablue::deltaBlue();::10"
  "crypto::encrypt(); decrypt();::1"
  "raytrace::renderScene();::1"
  "earley-boyer::BgL_earleyzd2benchmarkzd2(); BgL_nboyerzd2benchmarkzd2();::1"
  "splay:SplaySetup();:SplayRun();:SplayTearDown();:20"
  "navier-stokes:setupNavierStokes();:runNavierStokes();:tearDownNavierStokes();:1"
)

cp "$SRC/LICENSE" "$DEST/LICENSE"

for spec in "${SPECS[@]}"; do
  IFS=: read -r name setup run teardown iters <<< "$spec"
  [ -f "$SRC/$name.js" ] || die "$SRC/$name.js missing"

  {
    echo "// GENERATED by scripts/octane-vendor.sh — do not edit by hand."
    echo "// Source: chromium/octane @ $SRC_SHA (BSD-3-Clause, see LICENSE here)."
    echo "//"
    echo "// Setup chunk for the $name workload: definitions, deterministic RNG"
    echo "// seeding, and setup. Run ONCE, outside the timed region."
    echo ""
    # Octane's shell harness provided print(); nothing here should print, but
    # base.js reaches for it on the error path.
    echo "if (typeof print === 'undefined') { var print = function () {}; }"
    echo ""
    cat "$SRC/base.js"
    cat "$SRC/$name.js"
    echo ""
    # Octane installs the seeded Math.random here rather than at load, so a
    # harness that skips this call gets a nondeterministic Splay and EarleyBoyer.
    echo "BenchmarkSuite.ResetRNG();"
    if [ -n "$setup" ]; then echo "$setup"; fi
    echo "true;"
  } > "$DEST/$name.js"

  {
    echo "// GENERATED by scripts/octane-vendor.sh — do not edit by hand."
    echo "//"
    echo "// Run chunk for the $name workload: $iters fixed iterations, measured"
    echo "// per op. Depends on globals the setup chunk defined, which survive"
    echo "// because Interpret() does not Reset()."
    echo "for (var __octane_i = 0; __octane_i < $iters; __octane_i++) { $run }"
    echo "true;"
  } > "$DEST/$name-run.js"

  # Teardown is a correctness check, not work to measure — SplayTearDown
  # validates the tree it built and throws if it is inconsistent. Emitted only
  # where one exists; bench_octane_test.go runs it once, after the timer stops.
  if [ -n "$teardown" ]; then
    {
      echo "// GENERATED by scripts/octane-vendor.sh — do not edit by hand."
      echo "//"
      echo "// Teardown chunk for $name. Run once after the timer stops: this"
      echo "// validates workload state and releases it, and is not measured."
      echo "$teardown"
      echo "true;"
    } > "$DEST/$name-teardown.js"
  fi

  note "$name  ($iters iterations/op$([ -n "$teardown" ] && echo ", with teardown"))"
done

note "vendored ${#SPECS[@]} workloads from octane @ $SRC_SHA into $DEST"
